name: Run Python CPU Monitor

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: pip install psutil requests

      - name: Run CPU Monitor Script
        run: python loop.py
